### ISSUE TITLE
Now it gives me errors

### ISSUE THREAD

**Issue by PhoenixTheCoder** [HoLLy-HaCKeR/bulletforcehax#6]
3442bff6-bc93-4dc0-8d34-6ab3f503617a:8 [ACTk] WallHack Detector: can't find 'Hidden/ACTk/WallHackTexture' shader!
Please make sure you have it included at the ACTk Settings widow. 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

_JS_Log_Dump @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26faa4
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26f9d3
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26f6bc
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26eb57
(anonymous) @ BF_739CrazyGames_prod.wasm:0x695545
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1723947
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1723996
(anonymous) @ BF_739CrazyGames_prod.wasm:0xf63b35
(anonymous) @ BF_739CrazyGames_prod.wasm:0x164fbe3
(anonymous) @ BF_739CrazyGames_prod.wasm:0xea1476
(anonymous) @ BF_739CrazyGames_prod.wasm:0x17234be
(anonymous) @ BF_739CrazyGames_prod.wasm:0x10127fb
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1012332
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1b9477c
(anonymous) @ BF_739CrazyGames_prod.wasm:0xe0fa69
dynCall_iiiii @ BF_739CrazyGames_prod.wasm:0x1c2a2f1
(anonymous) @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
invoke_iiiii @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1ad14ce
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1aaeb0d
(anonymous) @ BF_739CrazyGames_prod.wasm:0x281513
(anonymous) @ BF_739CrazyGames_prod.wasm:0x2811eb
(anonymous) @ BF_739CrazyGames_prod.wasm:0x3c355b
(anonymous) @ BF_739CrazyGames_prod.wasm:0x3c237d
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4d79a4
(anonymous) @ BF_739CrazyGames_prod.wasm:0x3ec0ad
(anonymous) @ BF_739CrazyGames_prod.wasm:0x504616
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4e1853
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4e1868
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4e1371
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4df2cd
dynCall_v @ BF_739CrazyGames_prod.wasm:0x1c2a554
(anonymous) @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
browserIterationFunc @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
runIter @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Show 7 more frames
3442bff6-bc93-4dc0-8d34-6ab3f503617a:8 [ACTk] Speed Hack Detector: has properly configured Detection Event in the inspector, but still get started with Action callback. Both Action and Detection Event will be called on detection. Are you sure you wish to do this? 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

_JS_Log_Dump @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26faa4
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26fa39
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26f6bc
(anonymous) @ BF_739CrazyGames_prod.wasm:0x26eb57
(anonymous) @ BF_739CrazyGames_prod.wasm:0x695545
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1723947
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1723996
(anonymous) @ BF_739CrazyGames_prod.wasm:0xf63b35
(anonymous) @ BF_739CrazyGames_prod.wasm:0x164fbe3
(anonymous) @ BF_739CrazyGames_prod.wasm:0xea1476
(anonymous) @ BF_739CrazyGames_prod.wasm:0x17236bf
(anonymous) @ BF_739CrazyGames_prod.wasm:0x100e78c
(anonymous) @ BF_739CrazyGames_prod.wasm:0x100e930
(anonymous) @ BF_739CrazyGames_prod.wasm:0x100e919
(anonymous) @ BF_739CrazyGames_prod.wasm:0x100e901
(anonymous) @ BF_739CrazyGames_prod.wasm:0x100e8eb
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1b947c3
(anonymous) @ BF_739CrazyGames_prod.wasm:0xe0fa69
dynCall_iiiii @ BF_739CrazyGames_prod.wasm:0x1c2a2f1
(anonymous) @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
invoke_iiiii @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1ad14ce
(anonymous) @ BF_739CrazyGames_prod.wasm:0x1aaeb0d
(anonymous) @ BF_739CrazyGames_prod.wasm:0x281513
(anonymous) @ BF_739CrazyGames_prod.wasm:0x2811eb
(anonymous) @ BF_739CrazyGames_prod.wasm:0x3c355b
(anonymous) @ BF_739CrazyGames_prod.wasm:0x3c237d
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4d79a4
(anonymous) @ BF_739CrazyGames_prod.wasm:0x3ec0ad
(anonymous) @ BF_739CrazyGames_prod.wasm:0x504616
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4e1853
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4e1868
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4e1371
(anonymous) @ BF_739CrazyGames_prod.wasm:0x4df2cd
dynCall_v @ BF_739CrazyGames_prod.wasm:0x1c2a554
(anonymous) @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
browserIterationFunc @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
runIter @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
requestAnimationFrame (async)
requestAnimationFrame @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_scheduler_rAF @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Browser_mainLoop_runner @ 3442bff6-bc93-4dc0-8d34-6ab3f503617a:8
Show 10 more frames
3442bff6-bc93-4dc0-8d34-6ab3f503617a:8 [ACTk] Injection Detector: is not supported on selected platform! 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by HoLLy-HaCKeR** [comment]
see #5
